// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// colsum_pmin1
NumericMatrix colsum_pmin1(NumericMatrix pm, NumericMatrix wm);
RcppExport SEXP _wHC_colsum_pmin1(SEXP pmSEXP, SEXP wmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type wm(wmSEXP);
    rcpp_result_gen = Rcpp::wrap(colsum_pmin1(pm, wm));
    return rcpp_result_gen;
END_RCPP
}
// get_2x2xk
NumericVector get_2x2xk(IntegerVector dis, IntegerVector cur_g, IntegerVector strata_int, int k);
RcppExport SEXP _wHC_get_2x2xk(SEXP disSEXP, SEXP cur_gSEXP, SEXP strata_intSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type dis(disSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cur_g(cur_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata_int(strata_intSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(get_2x2xk(dis, cur_g, strata_int, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wHC_colsum_pmin1", (DL_FUNC) &_wHC_colsum_pmin1, 2},
    {"_wHC_get_2x2xk", (DL_FUNC) &_wHC_get_2x2xk, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wHC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
