# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colsum_pmin1 <- function(pm, wm) {
    .Call('_wHC_colsum_pmin1', PACKAGE = 'wHC', pm, wm)
}

get_2x2xk <- function(dis, cur_g, strata_int, k) {
    .Call('_wHC_get_2x2xk', PACKAGE = 'wHC', dis, cur_g, strata_int, k)
}

